http:
  host: "0.0.0.0"
  port: "8081"
  
webService:
  wsdl: "http://soap-order-ws-v2.us-e1.cloudhub.io/service/BasicHttpBinding_IOrderService?wsdl"
  service: "service"
  port: "BasicHttpBinding_IOrderService"
  address: "http://soap-order-ws-v2.us-e1.cloudhub.io/service/BasicHttpBinding_IOrderService"
  
autoDiscovery:
  ID: "17521559"
  flowName: "prt-orders-sys-api-main"